title: NCHS Computer Science
description: Intermediated Data Programming (IDP) & Advanced Topics (Java)
theme: just-the-docs

url: https://nchs-cs.github.io/

aux_links:
  Markdown File Access: https://github.com/NCHS-CS/nchs-cs.github.io

logo: "/static/updatePNG_NCHS_JaguarHeadLogo__2__small.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # Docs: https://www.jsdelivr.com/package/npm/mermaid 
  version: "11.5.0"

callouts:
  notice:
    title: Notice
    color: blue
  warning:
    title: Warning
    color: yellow
  alert:
    title: Alert
    color: red

# sass:
#   quiet_deps: true

include:
  - idp/static

keep_files:
  - idp/static

defaults:
  - scope:
      path: "idp/resources/"  # The folder where your markdown files reside
      type: "pages"        # Pages that are in this folder
    values:
      parent: IDP Resources
